<?php

$assetUrl = $this->plugin('assetUrl');

$this->headScript()->appendFile($assetUrl('dist/index.umd.js', 'Transcript'), 'module');
$this->headLink()->appendStylesheet($assetUrl('dist/style.css', 'Transcript'));

// Vimeo API shows wrong MIME type for adaptive bitrate files
$mimeTypes = [
    'hls' => 'application/vnd.apple.mpegurl',
    'dash' => 'application/dash+xml'
];

// Remove unneeded keys from payload
$allowedKeys = array_flip([
    'type',
    'rendition',
    'link'
]);

foreach ($links as &$link) {
    if (isset($link['quality']) && isset($mimeTypes[$link['quality']])) {
        $link['type'] = $mimeTypes[$link['quality']];
    }
    $link = array_intersect_key($link, $allowedKeys);
}
unset($link);

// Sort by resolution name
usort($links, function ($a, $b) {
    return -strnatcmp($a['rendition'], $b['rendition']);
});

$props = htmlspecialchars(json_encode([
    'type' => $type,
    'links' => $links,
    'textTracks' => $texttracks,
    'defaultTrack' => $default,
    'poster' => $poster ?? false,
    'color' => $color,
    'compactMode' => $compactMode,
    'hideTranscript' => $hideTranscript
]));

?>

<div class="player-root" data-props="<?= $props ?>"></div>