<?php

$assetUrl = $this->plugin('assetUrl');

$this->headScript()->appendFile($assetUrl('js/hls.min.js', 'Transcript'));
$this->headScript()->appendFile($assetUrl('js/transcript.js', 'Transcript'));
$this->headLink()->appendStylesheet($assetUrl('css/style.min.css', 'Transcript'));

if ($multiRes = count($links) > 1) {
    // Vimeo API shows wrong MIME type for adaptive bitrate files
    $mimeTypes = [
        'hls' => 'application/vnd.apple.mpegurl',
        'dash' => 'application/dash+xml'
    ];
    
    foreach ($links as &$link) {
        if (isset($mimeTypes[$link['quality']])) {
            $link['type'] = $mimeTypes[$link['quality']];
        }
    }
    unset($link);
    
    // Sort by resolution name
    usort($links, function ($a, $b) {
        return -strnatcmp($a['rendition'], $b['rendition']);
    });
}

?>

<div class="player-container player-video<?php if ($compactMode): ?> player-compact<?php endif; ?>"
    <?php if ($color): ?> style="--player-color: <?= $color ?>" <?php endif; ?>
    aria-label="<?= $this->translate('Video player') ?>" role="region">
    <div class="player-aspect paused">
        <?php if (isset($poster)): ?>
            <img class="player-poster front" src="<?= $poster ?>" crossorigin="anonymous">
        <?php endif; ?>
        
        <video preload="auto" playsinline crossorigin="anonymous">
            <?php foreach ($links as $link): ?>
                <source src="<?= $link['link'] ?>"
                    type="<?= $link['type'] ?>"
                    <?php if ($multiRes): ?>
                        data-resolution="<?= $link['rendition'] ?>"
                    <?php endif; ?>>
            <?php endforeach; ?>
            
            <?php if (!$hideTranscript): ?>
                <?php foreach ($texttracks as $track): ?>
                    <track src="<?= $track['storage'] ?>"
                        srclang="<?= $track['language'] ?>"
                        kind="metadata">
                <?php endforeach; ?>
            <?php endif; ?>
        </video>
        
        <div class="player-cellophane"></div>
        <div class="player-controls">
            <button class="player-playpause fa fa-play"
                aria-label="<?= $this->translate('Play') ?>"
                data-label-play="<?= $this->translate('Play') ?>"
                data-label-pause="<?= $this->translate('Pause') ?>"></button>
            <div class="player-timecode-container">
                <input class="player-timecode" type="range"
                    min="0" value="0" step="0.1"
                    aria-label="<?= $this->translate('Timecode') ?>"
                    aria-valuetext="0:00" />
                <span class="player-timecode-tooltip" aria-hidden="true">0:00</span>
                <progress class="player-buffer" value="0" max="1" aria-hidden="true"></progress>
            </div>
            <span class="player-duration"
                aria-label="<?= $this->translate('Duration') ?>">0:00</span>
            <button class="player-mute fa fa-volume-up"
                aria-label="<?= $this->translate('Mute') ?>"
                data-label-mute="<?= $this->translate('Mute') ?>"
                data-label-unmute="<?= $this->translate('Unmute') ?>"></button>
            <input class="player-volume" type="range"
                min="0" max="1" value="1" step="0.01"
                aria-label="<?= $this->translate('Volume') ?>"
                aria-valuetext="100%"
                style="--value: 100%" />
            
            <?php if ($multiRes): ?>
                <div class="player-settings-container">
                    <button class="player-settings fa fa-cog"
                        aria-label="<?= $this->translate('Settings') ?>"></button>
                        
                    <ul class="player-settings-list" role="radiogroup">
                        <li><a class="radio checked">Auto</a></li>
                        <?php foreach ($links as $link): ?>
                            <?php if ($link['rendition'] == "adaptive") { continue; } ?>
                            <li><a class="radio"><?= $link['rendition']; ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            
            <button class="player-pip fa fa-external-link-square-alt"
                aria-label="<?= $this->translate('Picture in picture') ?>"></button>
            <button class="player-fullscreen fa fa-expand"
                aria-label="<?= $this->translate('Fullscreen') ?>"
                data-label-open="<?= $this->translate('Fullscreen') ?>"
                data-label-close="<?= $this->translate('Exit fullscreen') ?>"></button>
        </div>
    </div>
    
    <?php if ($texttracks && !$hideTranscript): ?>
        <?= $this->partial('common/transcript-sidebar', [
            'texttracks' => $texttracks,
            'default' => $default
        ]); ?>
    <?php endif; ?>
</div>