<?php

$assetUrl = $this->plugin('assetUrl');

$this->headScript()->appendFile($assetUrl('js/hls.min.js', 'VimeoEmbed'));
$this->headScript()->appendFile($assetUrl('js/vimeo.js', 'VimeoEmbed'));
$this->headLink()->appendStylesheet($assetUrl('css/style.min.css', 'VimeoEmbed'));

// Vimeo API shows wrong MIME type for adaptive bitrate files
$mimeTypes = [
    'hls' => 'application/vnd.apple.mpegurl',
    'dash' => 'application/dash+xml'
];

foreach ($links as &$link) {
    if (isset($mimeTypes[$link['quality']])) {
        $link['type'] = $mimeTypes[$link['quality']];
    }
}
unset($link);

// Sort by resolution name
usort($links, function ($a, $b) {
    return -strnatcmp($a['rendition'], $b['rendition']);
});

?>

<div class="vimeo-container" role="region" aria-label="<?= $this->translate('Video player') ?>"
    <?php if ($color): ?> style="--vimeo-color: <?= $color ?>" <?php endif; ?>>
    <div class="vimeo-aspect paused">
        <video poster="<?= $poster ?>" preload="metadata" playsinline>
            <?php foreach ($links as $link): ?>
                <source src="<?= $link['link'] ?>"
                    type="<?= $link['type'] ?>"
                    data-resolution="<?= $link['rendition'] ?>">
            <?php endforeach; ?>
            
            <?php foreach ($texttracks as $track): ?>
                <track src="<?= $track['storage'] ?>"
                    srclang="<?= $track['language'] ?>"
                    kind="metadata">
            <?php endforeach; ?>
        </video>
        <div class="vimeo-cellophane"></div>
        <div class="vimeo-controls">
            <button class="vimeo-playpause fa fa-play"
                aria-label="<?= $this->translate('Play') ?>"
                data-label-play="<?= $this->translate('Play') ?>"
                data-label-pause="<?= $this->translate('Pause') ?>"></button>
            <div class="vimeo-timecode-container">
                <input class="vimeo-timecode" type="range"
                    min="0" value="0" step="0.1"
                    aria-label="<?= $this->translate('Timecode') ?>"
                    aria-valuetext="0:00" />
                <span class="vimeo-timecode-tooltip" aria-hidden="true">0:00</span>
                <progress class="vimeo-buffer" value="0" max="1" aria-hidden="true"></progress>
            </div>
            <span class="vimeo-duration"
                aria-label="<?= $this->translate('Duration') ?>">0:00</span>
            <button class="vimeo-mute fa fa-volume-up"
                aria-label="<?= $this->translate('Mute') ?>"
                data-label-mute="<?= $this->translate('Mute') ?>"
                data-label-unmute="<?= $this->translate('Unmute') ?>"></button>
            <input class="vimeo-volume" type="range"
                min="0" max="1" value="1" step="0.01"
                aria-label="<?= $this->translate('Volume') ?>"
                aria-valuetext="100%"
                style="--value: 100%" />
            
            <div class="vimeo-settings-container">
                <button class="vimeo-settings fa fa-cog"
                    aria-label="<?= $this->translate('Settings') ?>"></button>
                    
                <ul class="vimeo-settings-list" role="radiogroup">
                    <li><a class="radio checked">Auto</a></li>
                    <?php foreach ($links as $link): ?>
                        <?php if ($link['rendition'] == "adaptive") { continue; } ?>
                        <li><a class="radio"><?= $link['rendition']; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            
            <button class="vimeo-pip fa fa-external-link-square-alt"
                aria-label="<?= $this->translate('Picture in picture') ?>"></button>
            <button class="vimeo-fullscreen fa fa-expand"
                aria-label="<?= $this->translate('Fullscreen') ?>"
                data-label-open="<?= $this->translate('Fullscreen') ?>"
                data-label-close="<?= $this->translate('Exit fullscreen') ?>"></button>
        </div>
    </div>
    
    <?php if ($texttracks): ?>
    <div class="vimeo-sidebar loading">
        <div class="vimeo-header">
            <select title="<?= $this->translate('Transcript language') ?>">
                <?php foreach ($texttracks as $track): ?>
                <option value="<?php echo $track['language']; ?>"
                    <?php if ($track['language'] == $default): ?> selected<?php endif; ?>>
                    <?php echo $track['language-label']; ?>
                </option>
                <?php endforeach; ?>
            </select>
            
            <button class="vimeo-close fas fa-times" title="<?= $this->translate('Close transcript') ?>"></button>
        </div>
        
        <div class="vimeo-track-container">
        </div>
    </div>
    <?php endif; ?>
</div>